### ISSUE TITLE
Implement Milestone 2 features

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#2]
- [x] Import scarped data to Pandas functionality
- [x] Implement data analytics and charting functionality from pandas data frame  
- [x] Generate pdf report from pandas with graphs
- [ ] Email pdf report as as attachment
- [ ] Fix bug incorrect view count
- [ ] Fix bug incorrect ad insert date

**Comment by vfedotovs** [comment]
Implemented email pdf report as as attachment

**Comment by vfedotovs** [comment]
Fixing correct Milestone 2 tag
